# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: domain_prefix 0.2.2.4 ruby lib

Gem::Specification.new do |s|
  s.name = "domain_prefix"
  s.version = "0.2.2.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["tadman"]
  s.date = "2014-02-27"
  s.description = "A library to extract information about top-level domain and registered name from generic and international domain names"
  s.email = "github@tadman.ca"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "data/effective_tld_names.dat",
    "domain_prefix.gemspec",
    "lib/domain_prefix.rb",
    "test/helper.rb",
    "test/sample/README",
    "test/sample/test.txt",
    "test/test_domain_prefix.rb"
  ]
  s.homepage = "http://github.com/twg/domain_prefix"
  s.rubygems_version = "2.2.0"
  s.summary = "Domain Prefix Extraction Library"
end

